[project]
name = "insitu_probe_generator"
version = "2.1.0"
description = "A short description of your project"
readme = "README.md"
requires-python = ">=3.7,<3.13"
dependencies = [
    "biopython>=1.81",
    "numpy>=1.21.6",
    "openpyxl>=3.1.3",
    "pandas>=1.1.5",
]


