[project]
name = "insitu_probe_generator"
version = "2.2.0"
requires-python = ">=3.8,<3.9"
description = "A short description of your project"
readme = "README.md"
dependencies = [
    "biopython>=1.81",
    "numpy<2.0",
    "openpyxl>=3.1.3",
    "pandas>=1.1.5",
]


